# https://supabase.com/docs/guides/cli/config
project_id = "qwerty-learner"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://qwerty-learner-3z4e.vercel.app/admin", "http://localhost:5173/admin"]

[auth.email]
enable_signup = true
enable_confirmations = false
